package com.sevenEleven.servlet.admin2;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.sevenEleven.javaBean.CConnectMSSQL;

/**
 * Servlet implementation class for Servlet: WeekSchemeMaker
 *
 */
 public class WeekSchemeMaker extends javax.servlet.http.HttpServlet implements javax.servlet.Servlet {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#HttpServlet()
	 */
	public WeekSchemeMaker() {
		super();
	}   	
	
	/* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doPost(request,response);
	}  	
	
	/* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		String cid = request.getParameter("cid");
		//System.out.print(cid);
		String A0111= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A011120070101' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db = new CConnectMSSQL();
		List A0111LIST = db.getNestedListFromResultSet(A0111);
		request.setAttribute("A0111", A0111LIST);
		//System.out.print(A0111LIST);
		
		String A0112= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A011220070101' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db2 = new CConnectMSSQL();
		List A0112LIST = db2.getNestedListFromResultSet(A0112);
		request.setAttribute("A0112", A0112LIST);
		
		String A0113= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A011320070101' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db3 = new CConnectMSSQL();
		List A0113LIST = db3.getNestedListFromResultSet(A0113);
		request.setAttribute("A0113", A0113LIST);
		
		String A0114= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A011420070101' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db4 = new CConnectMSSQL();
		List A0114LIST = db4.getNestedListFromResultSet(A0114);
		request.setAttribute("A0114", A0114LIST);
		
		String A0121= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A012120070102' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db5 = new CConnectMSSQL();
		List A0121LIST = db5.getNestedListFromResultSet(A0121);
		request.setAttribute("A0121", A0121LIST);
		
		String A0122= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A012220070102' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db6 = new CConnectMSSQL();
		List A0122LIST = db6.getNestedListFromResultSet(A0122);
		request.setAttribute("A0122", A0122LIST);
		
		String A0123= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A012320070102' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db7 = new CConnectMSSQL();
		List A0123LIST = db7.getNestedListFromResultSet(A0123);
		request.setAttribute("A0123", A0123LIST);
		
		String A0124= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A012420070102' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db8 = new CConnectMSSQL();
		List A0124LIST = db8.getNestedListFromResultSet(A0124);
		request.setAttribute("A0124", A0124LIST);
		
		String A0131= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0131' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db9 = new CConnectMSSQL();
		List A0131LIST = db9.getNestedListFromResultSet(A0131);
		request.setAttribute("A0131", A0131LIST);
		
		String A0132= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0132' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db10 = new CConnectMSSQL();
		List A0132LIST = db10.getNestedListFromResultSet(A0132);
		request.setAttribute("A0132", A0132LIST);
		
		String A0133= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0133' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db11 = new CConnectMSSQL();
		List A0133LIST = db11.getNestedListFromResultSet(A0133);
		request.setAttribute("A0133", A0133LIST);
		
		String A0134= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0134' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db12 = new CConnectMSSQL();
		List A0134LIST = db12.getNestedListFromResultSet(A0134);
		request.setAttribute("A0134", A0134LIST);
		
		String A0141= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0141' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db13 = new CConnectMSSQL();
		List A0141LIST = db13.getNestedListFromResultSet(A0141);
		request.setAttribute("A0141", A0141LIST);
		
		String A0142= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0142' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db14 = new CConnectMSSQL();
		List A0142LIST = db14.getNestedListFromResultSet(A0142);
		request.setAttribute("A0142", A0142LIST);
		
		String A0143= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0143' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db15 = new CConnectMSSQL();
		List A0143LIST = db15.getNestedListFromResultSet(A0143);
		request.setAttribute("A0143", A0143LIST);
		
		String A0144= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0144' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db16 = new CConnectMSSQL();
		List A0144LIST = db16.getNestedListFromResultSet(A0144);
		request.setAttribute("A0144", A0144LIST);
		
		String A0151= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0151' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db17 = new CConnectMSSQL();
		List A0151LIST = db17.getNestedListFromResultSet(A0151);
		request.setAttribute("A0151", A0151LIST);
		
		String A0152= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0152' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db18 = new CConnectMSSQL();
		List A0152LIST = db18.getNestedListFromResultSet(A0152);
		request.setAttribute("A0152", A0152LIST);
		
		String A0153= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0153' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db19 = new CConnectMSSQL();
		List A0153LIST = db19.getNestedListFromResultSet(A0153);
		request.setAttribute("A0153", A0153LIST);
		
		String A0154= "SELECT TIME.TIME_ID,C_NAME,L1_NAME,T_NAME,CR_NAME FROM CLASS,TIME,LESSON1,TEACHER,CLASSROOM,LESSON1_LIST WHERE CLASS.C_ID=LESSON1_LIST.C_ID AND TIME.TIME_ID=LESSON1_LIST.TIME_ID AND LESSON1.L1_ID=LESSON1_LIST.L1_ID AND TEACHER.T_ID=LESSON1_LIST.T_ID AND CLASSROOM.CR_ID=LESSON1_LIST.CR_ID AND LESSON1_LIST.TIME_ID='A0154' AND LESSON1_LIST.C_ID="+cid;
		CConnectMSSQL db20 = new CConnectMSSQL();
		List A0154LIST = db20.getNestedListFromResultSet(A0154);
		request.setAttribute("A0154", A0154LIST);
		
		request.getRequestDispatcher("find_one_scheme_in_all.jsp").forward(request,
				response);	
		
		
		
	}   	  	    
}