package com.tsinghuait.st0717.hospitalsystem.dto;



/**
 * SickbedId generated by MyEclipse - Hibernate Tools
 */

public class SickbedId  implements java.io.Serializable {
     private Integer id;
     private String bedNo;
     private Integer type;
     private String nurseIds;
    /** default constructor */
    public SickbedId() {
    }

    
    /** full constructor */
    public SickbedId(Integer id, String bedNo, Integer type, String nurseIds) {
        this.id = id;
        this.bedNo = bedNo;
        this.type = type;
        this.nurseIds = nurseIds;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBedNo() {
        return this.bedNo;
    }
    
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo;
    }

    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    public String getNurseIds() {
        return this.nurseIds;
    }
    
    public void setNurseIds(String nurseIds) {
        this.nurseIds = nurseIds;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SickbedId) ) return false;
		 SickbedId castOther = ( SickbedId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getBedNo()==castOther.getBedNo()) || ( this.getBedNo()!=null && castOther.getBedNo()!=null && this.getBedNo().equals(castOther.getBedNo()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getNurseIds()==castOther.getNurseIds()) || ( this.getNurseIds()!=null && castOther.getNurseIds()!=null && this.getNurseIds().equals(castOther.getNurseIds()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getBedNo() == null ? 0 : this.getBedNo().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getNurseIds() == null ? 0 : this.getNurseIds().hashCode() );
         return result;
   }   





}