package com.tsinghuait.st0717.hospitalsystem.dto;

import java.util.Date;


/**
 * SinkbedSchedule generated by MyEclipse - Hibernate Tools
 */

public class SinkbedSchedule  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer sinkbedId;
     private Date startTime;
     private Date endTime;
     private Integer operationId;


    // Constructors

    /** default constructor */
    public SinkbedSchedule() {
    }

	/** minimal constructor */
    public SinkbedSchedule(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public SinkbedSchedule(Integer id, Integer sinkbedId, Date startTime, Date endTime, Integer operationId) {
        this.id = id;
        this.sinkbedId = sinkbedId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.operationId = operationId;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSinkbedId() {
        return this.sinkbedId;
    }
    
    public void setSinkbedId(Integer sinkbedId) {
        this.sinkbedId = sinkbedId;
    }

    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Integer getOperationId() {
        return this.operationId;
    }
    
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }
   








}