/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ssh.dao.IUserDao;
import com.ssh.pojo.UserInfo;
import com.ssh.struts.form.RegisterForm;

/**
 * MyEclipse Struts Creation date: 04-02-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/register" name="registerForm" input="/register.jsp"
 *                scope="request" validate="true"
 */
public class RegisterAction extends DispatchAction {
	private IUserDao userDao;

	/*
	 * Generated Methods
	 */

	public IUserDao getUserDao() {
		return userDao;
	}

	public void setUserDao(IUserDao userDao) {
		this.userDao = userDao;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated
		// method stub
		UserInfo userInfo = new UserInfo();
		userInfo.setAge(registerForm.getAge());
		userInfo.setUserName(registerForm.getUserName());
		try {
			this.getUserDao().save(userInfo);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			// e.printStackTrace();
			return mapping.findForward("error");
		}
		return mapping.findForward("ok");
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated
		UserInfo userInfo = null; // method stub
		List list = null;
		try {
			userInfo = this.userDao.queryByName(registerForm.getUserName());
			list = this.userDao.queryAllUser();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (userInfo != null) {
			request.setAttribute("list",list);
			return mapping.findForward("main");
		} else {
			return mapping.findForward("index");
		}
	}
}