package com.tsinghuait.st0717.hospitalsystem.dto;

import java.util.Date;


/**
 * OperationSchedule generated by MyEclipse - Hibernate Tools
 */

public class OperationSchedule  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer operationRoomId;
     private Integer operationId;
     private Date startTime;
     private Date endTime;


    // Constructors

    /** default constructor */
    public OperationSchedule() {
    }

	/** minimal constructor */
    public OperationSchedule(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public OperationSchedule(Integer id, Integer operationRoomId, Integer operationId, Date startTime, Date endTime) {
        this.id = id;
        this.operationRoomId = operationRoomId;
        this.operationId = operationId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOperationRoomId() {
        return this.operationRoomId;
    }
    
    public void setOperationRoomId(Integer operationRoomId) {
        this.operationRoomId = operationRoomId;
    }

    public Integer getOperationId() {
        return this.operationId;
    }
    
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
   








}