package com.tsinghuait.st0717.hospitalsystem.dto;



/**
 * Post generated by MyEclipse - Hibernate Tools
 */

public class Post  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;


    // Constructors

    /** default constructor */
    public Post() {
    }

	/** minimal constructor */
    public Post(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Post(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   








}